-- ===================================================
-- SUPABASE POSTGRESQL SCHEMA FOR IT-FESTIVAL 2026
-- ===================================================
-- Salin seluruh isi file ini, lalu jalankan di:
-- Dashboard Supabase -> Menu "SQL Editor" -> "New query" -> Run
-- ===================================================

-- 1. DROP EXISTING TABLES IF RE-CREATING
DROP TABLE IF EXISTS sponsors CASCADE;
DROP TABLE IF EXISTS media_partners CASCADE;
DROP TABLE IF EXISTS timeline CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS speakers CASCADE;

-- 2. TABEL SPONSORS
CREATE TABLE sponsors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT NOT NULL,
  website_url TEXT,
  is_visible BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL MEDIA PARTNERS
CREATE TABLE media_partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT NOT NULL,
  website_url TEXT,
  is_visible BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL TIMELINE AGENDA
CREATE TABLE timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date_string TEXT NOT NULL,
  category TEXT DEFAULT 'AGENDA',
  badge_color TEXT DEFAULT 'pink',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL EVENTS (KOMPETISI, PELATIHAN, SEMINAR)
CREATE TABLE events (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  category_label TEXT NOT NULL,
  description TEXT,
  icon_type TEXT DEFAULT 'code',
  badge_color TEXT DEFAULT 'cyan',
  gform_url TEXT DEFAULT 'https://forms.google.com/',
  guidebook_url TEXT DEFAULT '',
  mascot_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABEL SPEAKERS (PEMATERI & CV)
CREATE TABLE speakers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'speaker',
  photo TEXT,
  photo_position TEXT DEFAULT 'center',
  cv TEXT,
  color TEXT DEFAULT 'pink',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Memberikan izin read & write untuk API Next.js
-- ===================================================

ALTER TABLE sponsors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read sponsors" ON sponsors FOR SELECT USING (true);
CREATE POLICY "Public insert sponsors" ON sponsors FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update sponsors" ON sponsors FOR UPDATE USING (true);
CREATE POLICY "Public delete sponsors" ON sponsors FOR DELETE USING (true);

ALTER TABLE media_partners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read media_partners" ON media_partners FOR SELECT USING (true);
CREATE POLICY "Public insert media_partners" ON media_partners FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update media_partners" ON media_partners FOR UPDATE USING (true);
CREATE POLICY "Public delete media_partners" ON media_partners FOR DELETE USING (true);

ALTER TABLE timeline ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read timeline" ON timeline FOR SELECT USING (true);
CREATE POLICY "Public insert timeline" ON timeline FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update timeline" ON timeline FOR UPDATE USING (true);
CREATE POLICY "Public delete timeline" ON timeline FOR DELETE USING (true);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read events" ON events FOR SELECT USING (true);
CREATE POLICY "Public insert events" ON events FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update events" ON events FOR UPDATE USING (true);
CREATE POLICY "Public delete events" ON events FOR DELETE USING (true);

ALTER TABLE speakers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read speakers" ON speakers FOR SELECT USING (true);
CREATE POLICY "Public insert speakers" ON speakers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update speakers" ON speakers FOR UPDATE USING (true);
CREATE POLICY "Public delete speakers" ON speakers FOR DELETE USING (true);

-- ===================================================
-- SEED DATA SPONSORS
-- ===================================================
INSERT INTO sponsors (name, logo_url, is_visible) VALUES
('Sewa Kamera', 'logos/sponsors/sewa_kamera.svg', true),
('Risa Florist & Co.', 'logos/sponsors/risa_florist.svg', true),
('Syneps Academy', 'logos/sponsors/syneps.svg', true),
('Cibubur IT Center', 'logos/sponsors/cibubur_it.svg', true),
('Bank BRI', 'logos/sponsors/bri.svg', true),
('Miss Bakers', 'logos/sponsors/miss_bakers.svg', true),
('PUSRI', 'logos/sponsors/pusri.svg', true);

-- ===================================================
-- SEED DATA MEDIA PARTNERS
-- ===================================================
INSERT INTO media_partners (name, logo_url, is_visible) VALUES
('HIMA IF', 'logos/media_partners/hima_if.svg', true),
('HMI', 'logos/media_partners/hmi.svg', true),
('CMS', 'logos/media_partners/cms.svg', true),
('HMJ AOK', 'logos/media_partners/hmj_aok.svg', true),
('BNCC', 'logos/media_partners/bncc.svg', true),
('HIMA ILKOM FMIPA UNNES', 'logos/media_partners/hima_ilkom.svg', true);

-- ===================================================
-- SEED DATA TIMELINE AGENDA (17 ITEMS)
-- ===================================================
INSERT INTO timeline (id, title, date_string, category, badge_color) OVERRIDING SYSTEM VALUE VALUES
(1, 'OPEN REGISTRATION SEMINAR, PERLOMBAAN DAN PELATIHAN (CYBER & WEB)', 'Senin, 10 Agustus 2026', 'REGISTRASI', 'pink'),
(2, 'Close Registration Pelatihan dan Seminar', 'Rabu, 9 September 2026', 'CLOSE REG', 'cyan'),
(3, 'Opening Ceremony IT Festival 2026', 'Rabu, 16 September 2026', 'OPENING', 'yellow'),
(4, 'Pelaksanaan Seminar & Talkshow', 'Rabu, 16 September 2026', 'SEMINAR', 'pink'),
(5, 'Pelatihan vibe Coding', '17-18 September, 21-22 September 2026', 'PELATIHAN', 'cyan'),
(6, 'Pelatihan Cyber', '23-25 September, 28 September 2026', 'PELATIHAN', 'yellow'),
(7, 'Close Registration Lomba Mobile legends & Free Fire', 'Kamis, 1 Oktober 2026', 'CLOSE REG', 'pink'),
(8, 'Pelaksanaan Technical Meeting Lomba Mobile Legends', 'Jum’at, 2 Oktober 2026', 'TM', 'cyan'),
(9, 'Pelaksanaan Lomba Mobile Legends', 'Sabtu, 3 Oktober 2026 (Online) – Minggu, 4 Oktober 2026 (Ofline)', 'LOMBA', 'yellow'),
(10, 'Pelaksanaan Technical Meeting Lomba Free Fire', 'Jum’at, 9 Oktober 2026', 'TM', 'pink'),
(11, 'Pelaksanaan Lomba Free Fire', 'Sabtu, 10 Oktober 2026 (Online) – Minggu, 11 Oktober 2026 (Ofline)', 'LOMBA', 'cyan'),
(12, 'Close Registration Lomba Vibe Coding , Capture the flag , Fotografi', 'Minggu, 11 Oktober 2026', 'CLOSE REG', 'pink'),
(13, 'Technical Meeting Vibe Coding , Capture the flag , Fotografi', 'Senin, 12 Oktober 2026', 'TM', 'yellow'),
(14, 'Pelaksaan Lomba Capture The Flag', 'Sabtu, 17 Oktober 2026', 'LOMBA', 'cyan'),
(15, 'Batas Pengumpulan Karya Vibe Coding dan Fotografi', 'Jum’at, 23 Oktober 2026', 'DEADLINE', 'pink'),
(16, 'Penjurian Lomba Vibe Coding Dan Fotografi', 'Jum’at 24 – 30 Oktober 2026', 'PENJURIAN', 'yellow'),
(17, 'Closing Ceremony IT Festival 2026 & Pengumuman Pemenang', 'Senin, 2 November 2026', 'CLOSING', 'cyan');

-- Sinkronisasi sequence identity id timeline
SELECT setval(pg_get_serial_sequence('timeline', 'id'), coalesce(max(id),0) + 1, false) FROM timeline;

-- ===================================================
-- SEED DATA EVENTS
-- ===================================================
INSERT INTO events (id, title, category, category_label, description, icon_type, badge_color, gform_url, guidebook_url, mascot_url) VALUES
('ml', 'Mobile Legends', 'kompetisi', 'KOMPETISI', 'Buktikan skill dan kerja sama timmu di arena Mobile Legends, raih kemenangan demi kemenangan.', 'gamepad', 'cyan', 'https://bit.ly/PendaftaranLombaMobileLegendsITFestival2026', '', '/maskot/mascot-ml.png'),
('ff', 'Free Fire', 'kompetisi', 'KOMPETISI', 'Turun ke medan pertempuran Free Fire, jadi yang terakhir bertahan dan raih Booyah!', 'flame', 'pink', 'https://bit.ly/PendaftaranLombaFreeFireITFestival2026', '', '/maskot/mascot-ff.png'),
('vibe-coding-comp', 'Vibe Coding Competition', 'kompetisi', 'KOMPETISI', 'Bangun aplikasi atau produk digital secepat mungkin menggunakan bantuan AI, untuk menciptakan kreativitas.', 'code', 'yellow', 'https://bit.ly/PendaftaranLombaVibeCodingITFestival2026', '', '/maskot/mascot-vibe-coding.png'),
('ctf-comp', 'Capture The Flag Competition', 'kompetisi', 'KOMPETISI', 'Uji kemampuan hacking dan keamanan sibermu dengan memecahkan berbagai tantangan CTF dari level pemula hingga expert.', 'shield', 'cyan', 'https://bit.ly/PendaftranLombaCaptureTheFlagITFestival2026', '', '/maskot/mascot-ctf.png'),
('photography-comp', 'Photography Competition', 'kompetisi', 'KOMPETISI', 'Tunjukkan sudut pandang kreatifmu lewat lensa kamera dan abadikan momen terbaik dalam kompetisi fotografi ini.', 'camera', 'pink', 'https://bit.ly/PendaftaranLombaPromtographyITFestival2026', '', '/maskot/mascot-photography.png'),
('vibe-coding-training', 'Vibe Coding', 'pelatihan', 'PELATIHAN', 'Belajar membangun aplikasi dan produk digital secara cepat dengan bantuan AI, dari ide sampai jadi produk nyata.', 'code', 'yellow', 'http://bit.ly/PendaftaranPelatihanVibeCodingITFestival2026', '', '/maskot/mascot-vibe-coding.png'),
('cyber-security-training', 'Cyber Security', 'pelatihan', 'PELATIHAN', 'Pelajari dasar-dasar keamanan siber, mulai dari deteksi celah keamanan hingga teknik perlindungan sistem.', 'shield', 'cyan', 'https://bit.ly/PendaftaranPelatihanCybersecurityITFestival2026', '', '/maskot/mascot-ctf.png'),
('seminar-itfest', 'Seminar IT-Festival 2026', 'seminar', 'SEMINAR', 'Ikuti seminar kami dan dapatkan wawasan berharga langsung dari para ahli di bidang teknologi.', 'mic', 'pink', 'https://bit.ly/PendaftaranSeminarITFestival2026', '', '/maskot/mascot-vibe-coding.png');

-- ===================================================
-- SEED DATA SPEAKERS
-- ===================================================
INSERT INTO speakers (id, name, role, category, photo, photo_position, cv, color) VALUES
('avip-syaifulloh', 'Avip Syaifulloh, S.T.', 'CEO WPU Course', 'guest-star', '/speakers/avip-syaifulloh.jpg', 'center 25%', '/speakers/cv-avip-syaifulloh.pdf', 'pink'),
('rahmi-liza', 'Rahmi Liza, S.Tr.Kom., M.Sc.', 'Software Engineer', 'speaker', '/speakers/rahmi-liza.jpg', 'center 60%', '/speakers/cv-rahmi-liza.pdf', 'cyan');
